import {
  Affiliate,
  Application,
  ReferralLink,
  ReferralClick,
  Referral,
  Customer,
  Commission,
  Payout,
  Coupon,
  Campaign,
  Tier,
  Bonus,
  FraudCase,
  MarketingAsset,
  Notification,
  AuditLog,
  CommissionRule,
} from '@/types/affiliate';

export const INITIAL_AFFILIATES: Affiliate[] = [
  {
    id: 'aff-1',
    name: 'James Wilson',
    email: 'james.wilson@coachhub.io',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    company: 'Youth Hoops Network',
    website: 'https://youthhoopsnetwork.com',
    phone: '+1 (555) 234-5678',
    country: 'United States',
    socialLinks: {
      twitter: '@jameswilsonhoops',
      youtube: 'YouthHoopsAcademy',
      instagram: '@jameswilson_coach',
    },
    promotionalChannels: ['YouTube (45K Subs)', 'Basketball Podcast', 'Email Newsletter (12k)', 'Coaching Clinics'],
    referralCode: 'JAMES123',
    tier: 'Silver',
    status: 'Active',
    joinDate: '2025-08-15',
    payoutMethod: 'PayPal',
    payoutDetails: 'james.wilson@coachhub.io',
    stats: {
      totalClicks: 1248,
      signups: 186,
      paidCustomers: 24, // Ready for milestone demo (24 -> 25 to reach Gold!)
      conversionRate: 0.059,
      totalRevenue: 8420,
      pendingCommission: 485,
      payableCommission: 720,
      totalEarned: 2840,
      currentBalance: 720,
    },
    notes: ['Top performing sports coach in the Midwest region', 'Requested custom coupon SQUADJAMES20'],
  },
  {
    id: 'aff-2',
    name: 'Sarah Mitchell',
    email: 'sarah@uksoccerdrills.co.uk',
    avatar: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=150&auto=format&fit=crop&q=80',
    company: 'UK Grassroots Soccer Hub',
    website: 'https://uksoccerdrills.co.uk',
    phone: '+44 20 7946 0912',
    country: 'United Kingdom',
    socialLinks: {
      twitter: '@sarah_grassroots',
      instagram: '@uksoccerdrills',
      linkedin: 'sarah-mitchell-fa',
    },
    promotionalChannels: ['FA Coaching Network', 'Instagram (80k)', 'Grassroots Blog'],
    referralCode: 'SARAHFIT',
    tier: 'Gold',
    status: 'Active',
    joinDate: '2025-05-10',
    payoutMethod: 'Bank Transfer',
    payoutDetails: 'Barclays UK - Sort: 20-04-15 Acct: 88392019',
    stats: {
      totalClicks: 2850,
      signups: 340,
      paidCustomers: 48,
      conversionRate: 0.072,
      totalRevenue: 16400,
      pendingCommission: 820,
      payableCommission: 1450,
      totalEarned: 5800,
      currentBalance: 1450,
    },
    notes: ['Premier partner for European soccer academies'],
  },
  {
    id: 'aff-3',
    name: 'Daniel Carter',
    email: 'dan@hockeygrowth.ca',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    company: 'Ontario Hockey Association Portal',
    website: 'https://hockeygrowth.ca',
    phone: '+1 (416) 555-0199',
    country: 'Canada',
    socialLinks: {
      twitter: '@hockeygrowthca',
      youtube: 'DanCarterHockey',
    },
    promotionalChannels: ['Minor Hockey Coaches Forum', 'Webinar Series', 'Podcast'],
    referralCode: 'COACHDAN',
    tier: 'Platinum',
    status: 'Active',
    joinDate: '2025-02-01',
    payoutMethod: 'Stripe Direct',
    payoutDetails: 'acct_1NJx8829FKKsL99',
    stats: {
      totalClicks: 5120,
      signups: 620,
      paidCustomers: 85,
      conversionRate: 0.081,
      totalRevenue: 34200,
      pendingCommission: 1250,
      payableCommission: 2890,
      totalEarned: 11970,
      currentBalance: 2890,
    },
    notes: ['VIP Partner - highest conversion rate in North America'],
  },
  {
    id: 'aff-4',
    name: 'Olivia Brown',
    email: 'olivia@swimclubtech.com',
    avatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150&auto=format&fit=crop&q=80',
    company: 'Aquatic Sports Media',
    website: 'https://swimclubtech.com',
    phone: '+1 (555) 789-0123',
    country: 'United States',
    socialLinks: {
      instagram: '@swimclubtech',
      twitter: '@olivia_aquatics',
    },
    promotionalChannels: ['Swimming Coaches Association Newsletter', 'Tech Reviews Blog'],
    referralCode: 'OLIVIASWIM',
    tier: 'Bronze',
    status: 'Active',
    joinDate: '2026-01-10',
    payoutMethod: 'PayPal',
    payoutDetails: 'olivia@swimclubtech.com',
    stats: {
      totalClicks: 430,
      signups: 42,
      paidCustomers: 6,
      conversionRate: 0.045,
      totalRevenue: 1890,
      pendingCommission: 120,
      payableCommission: 240,
      totalEarned: 480,
      currentBalance: 240,
    },
  },
  {
    id: 'aff-5',
    name: 'Michael Anderson',
    email: 'm.anderson@volleyballcoach.org',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
    company: 'National Volleyball Directors',
    website: 'https://volleyballcoach.org',
    phone: '+1 (555) 345-6789',
    country: 'United States',
    socialLinks: {
      linkedin: 'michael-anderson-vball',
    },
    promotionalChannels: ['Club Director Summit', 'Direct Outreach'],
    referralCode: 'VBALLPRO',
    tier: 'Silver',
    status: 'Active',
    joinDate: '2025-09-20',
    payoutMethod: 'Wise',
    payoutDetails: 'michael.anderson.wise@gmail.com',
    stats: {
      totalClicks: 890,
      signups: 98,
      paidCustomers: 14,
      conversionRate: 0.051,
      totalRevenue: 4950,
      pendingCommission: 245,
      payableCommission: 490,
      totalEarned: 1420,
      currentBalance: 490,
    },
  },
  {
    id: 'aff-6',
    name: 'Emma Taylor',
    email: 'emma@netballleaders.com.au',
    avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80',
    company: 'Aussie Netball Resource',
    website: 'https://netballleaders.com.au',
    phone: '+61 2 9876 5432',
    country: 'Australia',
    socialLinks: {
      instagram: '@aussienetballtech',
    },
    promotionalChannels: ['Netball Australia Coaches Group', 'Weekly Newsletter'],
    referralCode: 'EMMANET',
    tier: 'Silver',
    status: 'Active',
    joinDate: '2025-10-05',
    payoutMethod: 'Bank Transfer',
    payoutDetails: 'Commonwealth Bank - BSB: 062-000 Acct: 10928374',
    stats: {
      totalClicks: 720,
      signups: 84,
      paidCustomers: 12,
      conversionRate: 0.048,
      totalRevenue: 3820,
      pendingCommission: 190,
      payableCommission: 380,
      totalEarned: 955,
      currentBalance: 380,
    },
  },
  {
    id: 'aff-7',
    name: 'David Thompson',
    email: 'david@rugbyadmin.co.nz',
    avatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150&auto=format&fit=crop&q=80',
    company: 'Kiwi Rugby Club Management',
    website: 'https://rugbyadmin.co.nz',
    phone: '+64 9 300 1234',
    country: 'New Zealand',
    socialLinks: {
      twitter: '@davidrugbyadmin',
    },
    promotionalChannels: ['NZ Rugby Clubs Directory', 'Regional Admin Workshops'],
    referralCode: 'KIWIRUGBY',
    tier: 'Bronze',
    status: 'Active',
    joinDate: '2025-11-18',
    payoutMethod: 'PayPal',
    payoutDetails: 'david@rugbyadmin.co.nz',
    stats: {
      totalClicks: 380,
      signups: 35,
      paidCustomers: 5,
      conversionRate: 0.039,
      totalRevenue: 1450,
      pendingCommission: 85,
      payableCommission: 150,
      totalEarned: 320,
      currentBalance: 150,
    },
  },
  {
    id: 'aff-8',
    name: 'Sophia Martinez',
    email: 'sophia@trackandfieldpros.com',
    avatar: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=150&auto=format&fit=crop&q=80',
    company: 'Athletics Director Hub',
    website: 'https://trackandfieldpros.com',
    phone: '+1 (555) 456-7890',
    country: 'United States',
    socialLinks: {
      twitter: '@sophiatrack',
      youtube: 'AthleticsCoachPro',
    },
    promotionalChannels: ['USTFCCCA Member Network', 'Athletics Blog'],
    referralCode: 'TRACKPRO',
    tier: 'Gold',
    status: 'Active',
    joinDate: '2025-06-12',
    payoutMethod: 'Stripe Direct',
    payoutDetails: 'acct_1LPs8849FKKsQ21',
    stats: {
      totalClicks: 1980,
      signups: 215,
      paidCustomers: 32,
      conversionRate: 0.063,
      totalRevenue: 11200,
      pendingCommission: 640,
      payableCommission: 1120,
      totalEarned: 3920,
      currentBalance: 1120,
    },
  },
  {
    id: 'aff-9',
    name: 'Lucas Garcia',
    email: 'lucas@padelclubs.es',
    avatar: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=150&auto=format&fit=crop&q=80',
    company: 'Iberian Padel Management',
    website: 'https://padelclubs.es',
    phone: '+34 91 123 4567',
    country: 'Spain',
    socialLinks: {
      instagram: '@lucas_padelpro',
    },
    promotionalChannels: ['Spanish Padel Federation Groups', 'Padel Magazine ES'],
    referralCode: 'PADELSPAIN',
    tier: 'Silver',
    status: 'Active',
    joinDate: '2025-07-28',
    payoutMethod: 'Bank Transfer',
    payoutDetails: 'Banco Santander - ES91 2100 0418 4502 0005 1332',
    stats: {
      totalClicks: 1120,
      signups: 130,
      paidCustomers: 18,
      conversionRate: 0.054,
      totalRevenue: 6240,
      pendingCommission: 310,
      payableCommission: 620,
      totalEarned: 1870,
      currentBalance: 620,
    },
  },
  {
    id: 'aff-10',
    name: 'Chloe Davis',
    email: 'chloe@lacrossegrowth.com',
    avatar: 'https://images.unsplash.com/photo-1524504388940-b1c1722653e1?w=150&auto=format&fit=crop&q=80',
    company: 'East Coast Lacrosse League Tech',
    website: 'https://lacrossegrowth.com',
    phone: '+1 (555) 678-9012',
    country: 'United States',
    socialLinks: {
      twitter: '@chloelax',
    },
    promotionalChannels: ['US Lacrosse Coaches Forum', 'LaxDirector Monthly'],
    referralCode: 'LAXPRO',
    tier: 'Bronze',
    status: 'Active',
    joinDate: '2026-02-05',
    payoutMethod: 'PayPal',
    payoutDetails: 'chloe@lacrossegrowth.com',
    stats: {
      totalClicks: 290,
      signups: 28,
      paidCustomers: 4,
      conversionRate: 0.041,
      totalRevenue: 1180,
      pendingCommission: 65,
      payableCommission: 120,
      totalEarned: 240,
      currentBalance: 120,
    },
  },
  {
    id: 'aff-11',
    name: 'Alexander Wright',
    email: 'alex@cricketcoachhub.com',
    avatar: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=150&auto=format&fit=crop&q=80',
    company: 'All-Round Cricket Coaching',
    website: 'https://cricketcoachhub.com',
    phone: '+44 161 834 9900',
    country: 'United Kingdom',
    socialLinks: { youtube: 'AlexWrightCricket' },
    promotionalChannels: ['Cricket Coaches UK Community', 'YouTube Drills'],
    referralCode: 'CRICKETPRO',
    tier: 'Silver',
    status: 'Active',
    joinDate: '2025-08-30',
    payoutMethod: 'Bank Transfer',
    payoutDetails: 'HSBC UK - 40-12-00 71829304',
    stats: { totalClicks: 840, signups: 92, paidCustomers: 13, conversionRate: 0.049, totalRevenue: 4320, pendingCommission: 215, payableCommission: 430, totalEarned: 1290, currentBalance: 430 },
  },
  {
    id: 'aff-12',
    name: 'Jessica Miller',
    email: 'jessica@gymnasticsmgmt.com',
    avatar: 'https://images.unsplash.com/photo-1567532939604-b6b5b0db2604?w=150&auto=format&fit=crop&q=80',
    company: 'Elite Gymnastics Club Directors',
    website: 'https://gymnasticsmgmt.com',
    phone: '+1 (555) 890-1234',
    country: 'United States',
    socialLinks: { instagram: '@jessicagymtech' },
    promotionalChannels: ['Gymnastics Owners Facebook Group (15k)', 'Industry Podcast'],
    referralCode: 'GYMDIRECTOR',
    tier: 'Gold',
    status: 'Active',
    joinDate: '2025-04-18',
    payoutMethod: 'PayPal',
    payoutDetails: 'jessica@gymnasticsmgmt.com',
    stats: { totalClicks: 1650, signups: 195, paidCustomers: 28, conversionRate: 0.061, totalRevenue: 9800, pendingCommission: 540, payableCommission: 980, totalEarned: 3430, currentBalance: 980 },
  },
  {
    id: 'aff-13',
    name: 'Marcus Vance',
    email: 'marcus@martialartsapp.com',
    avatar: 'https://images.unsplash.com/photo-1492562080023-ab3db95bfbce?w=150&auto=format&fit=crop&q=80',
    company: 'Dojo & Academy Software Reviews',
    website: 'https://martialartsapp.com',
    phone: '+1 (555) 901-2345',
    country: 'United States',
    socialLinks: { youtube: 'MarcusDojoTech' },
    promotionalChannels: ['BJJ / Martial Arts Schools Network', 'Software Review Blog'],
    referralCode: 'DOJOTECH',
    tier: 'Silver',
    status: 'Active',
    joinDate: '2025-09-14',
    payoutMethod: 'Stripe Direct',
    payoutDetails: 'acct_1MKa9921DJSks3',
    stats: { totalClicks: 950, signups: 104, paidCustomers: 15, conversionRate: 0.052, totalRevenue: 5200, pendingCommission: 260, payableCommission: 520, totalEarned: 1560, currentBalance: 520 },
  },
  {
    id: 'aff-14',
    name: 'Elena Rostova',
    email: 'elena@tennisacademy.de',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    company: 'European Tennis Coaches Alliance',
    website: 'https://tennisacademy.de',
    phone: '+49 89 1234567',
    country: 'Germany',
    socialLinks: { twitter: '@elena_tennis_de' },
    promotionalChannels: ['DTB Coaches Portal', 'Tennis Magazin DE'],
    referralCode: 'TENNISPRO',
    tier: 'Bronze',
    status: 'Active',
    joinDate: '2026-01-22',
    payoutMethod: 'Bank Transfer',
    payoutDetails: 'Deutsche Bank - DE89 3704 0044 0532 0130 00',
    stats: { totalClicks: 320, signups: 31, paidCustomers: 4, conversionRate: 0.038, totalRevenue: 1350, pendingCommission: 70, payableCommission: 135, totalEarned: 270, currentBalance: 135 },
  },
  {
    id: 'aff-15',
    name: 'Brandon Hall',
    email: 'brandon@baseballmanagers.org',
    avatar: 'https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?w=150&auto=format&fit=crop&q=80',
    company: 'Youth Baseball Directors Association',
    website: 'https://baseballmanagers.org',
    phone: '+1 (555) 012-3456',
    country: 'United States',
    socialLinks: { twitter: '@brandon_baseball' },
    promotionalChannels: ['Travel Ball Directors Group', 'Monthly Clinic'],
    referralCode: 'BASEBALL99',
    tier: 'Gold',
    status: 'Active',
    joinDate: '2025-05-25',
    payoutMethod: 'PayPal',
    payoutDetails: 'brandon@baseballmanagers.org',
    stats: { totalClicks: 2100, signups: 240, paidCustomers: 36, conversionRate: 0.065, totalRevenue: 12800, pendingCommission: 690, payableCommission: 1280, totalEarned: 4480, currentBalance: 1280 },
  },
  {
    id: 'aff-16',
    name: 'Hannah Abbott',
    email: 'hannah@cheercoaches.com',
    avatar: 'https://images.unsplash.com/photo-1548142813-c348350df52b?w=150&auto=format&fit=crop&q=80',
    company: 'All-Star Cheer Management',
    website: 'https://cheercoaches.com',
    phone: '+1 (555) 123-9876',
    country: 'United States',
    socialLinks: { instagram: '@cheer_admin_pro' },
    promotionalChannels: ['Cheer Gym Owners Forum', 'Webinar Presentations'],
    referralCode: 'CHEERTECH',
    tier: 'Bronze',
    status: 'Active',
    joinDate: '2026-02-14',
    payoutMethod: 'PayPal',
    payoutDetails: 'hannah@cheercoaches.com',
    stats: { totalClicks: 210, signups: 19, paidCustomers: 3, conversionRate: 0.035, totalRevenue: 980, pendingCommission: 50, payableCommission: 98, totalEarned: 196, currentBalance: 98 },
  },
  {
    id: 'aff-17',
    name: 'Noah Bennett',
    email: 'noah@climbinggyms.co',
    avatar: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=150&auto=format&fit=crop&q=80',
    company: 'Climbing Wall & Gym Network',
    website: 'https://climbinggyms.co',
    phone: '+1 (555) 234-8765',
    country: 'United States',
    socialLinks: { twitter: '@noah_climbtech' },
    promotionalChannels: ['CWA Members Portal', 'Climbing Gym Tech Reviews'],
    referralCode: 'CLIMBTECH',
    tier: 'Silver',
    status: 'Active',
    joinDate: '2025-10-19',
    payoutMethod: 'Wise',
    payoutDetails: 'noah.bennett.wise@gmail.com',
    stats: { totalClicks: 680, signups: 74, paidCustomers: 10, conversionRate: 0.046, totalRevenue: 3400, pendingCommission: 170, payableCommission: 340, totalEarned: 850, currentBalance: 340 },
  },
  {
    id: 'aff-18',
    name: 'Liam O’Connor',
    email: 'liam@gaacoaches.ie',
    avatar: 'https://images.unsplash.com/photo-1501196354995-cbb51c65aaea?w=150&auto=format&fit=crop&q=80',
    company: 'Irish Gaelic Sports Admin Hub',
    website: 'https://gaacoaches.ie',
    phone: '+353 1 496 0123',
    country: 'Ireland',
    socialLinks: { twitter: '@liam_gaatech' },
    promotionalChannels: ['GAA Club Secretaries Network', 'County Board Circular'],
    referralCode: 'GAACLUB',
    tier: 'Bronze',
    status: 'Active',
    joinDate: '2025-12-01',
    payoutMethod: 'Bank Transfer',
    payoutDetails: 'Bank of Ireland - IE12 BOFI 9000 1712 3456 78',
    stats: { totalClicks: 340, signups: 32, paidCustomers: 4, conversionRate: 0.039, totalRevenue: 1240, pendingCommission: 65, payableCommission: 124, totalEarned: 248, currentBalance: 124 },
  },
  {
    id: 'aff-19',
    name: 'Mia Roberts',
    email: 'mia@dancestudiotech.com',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    company: 'Dance Studio Owners Collective',
    website: 'https://dancestudiotech.com',
    phone: '+1 (555) 345-7654',
    country: 'United States',
    socialLinks: { instagram: '@miadancetech' },
    promotionalChannels: ['Dance Teacher Summit', 'Email List (8k)'],
    referralCode: 'DANCEPRO',
    tier: 'Silver',
    status: 'Active',
    joinDate: '2025-08-11',
    payoutMethod: 'PayPal',
    payoutDetails: 'mia@dancestudiotech.com',
    stats: { totalClicks: 820, signups: 89, paidCustomers: 12, conversionRate: 0.048, totalRevenue: 4100, pendingCommission: 205, payableCommission: 410, totalEarned: 1025, currentBalance: 410 },
  },
  {
    id: 'aff-20',
    name: 'Victor Vance',
    email: 'victor@suspicious-traffic.xyz',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    company: 'Global Sports Leads LLC',
    website: 'https://globalsportsleads.xyz',
    phone: '+1 (555) 000-1111',
    country: 'United States',
    socialLinks: {},
    promotionalChannels: ['Automated Banner Exchange', 'Pop-under Networks'],
    referralCode: 'SPAMTECH',
    tier: 'Bronze',
    status: 'Suspended',
    joinDate: '2026-01-05',
    payoutMethod: 'PayPal',
    payoutDetails: 'victor@suspicious-traffic.xyz',
    stats: { totalClicks: 1420, signups: 12, paidCustomers: 0, conversionRate: 0.002, totalRevenue: 0, pendingCommission: 0, payableCommission: 0, totalEarned: 0, currentBalance: 0 },
    notes: ['Suspended for high volume click spam and spoofed IP traffic'],
  },
  {
    id: 'aff-21',
    name: 'Rebecca Scott',
    email: 'rebecca@equestrianclubs.com',
    avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80',
    company: 'Equestrian Center Management',
    website: 'https://equestrianclubs.com',
    phone: '+1 (555) 678-1234',
    country: 'United States',
    socialLinks: { linkedin: 'rebecca-scott-equestrian' },
    promotionalChannels: ['USEF Club Directory', 'Barn Management Blog'],
    referralCode: 'HORSETECH',
    tier: 'Bronze',
    status: 'Active',
    joinDate: '2026-02-20',
    payoutMethod: 'PayPal',
    payoutDetails: 'rebecca@equestrianclubs.com',
    stats: { totalClicks: 180, signups: 16, paidCustomers: 2, conversionRate: 0.036, totalRevenue: 780, pendingCommission: 40, payableCommission: 78, totalEarned: 156, currentBalance: 78 },
  },
  {
    id: 'aff-22',
    name: 'Carlos Mendoza',
    email: 'carlos@futbolmexico.mx',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
    company: 'Academias de Fútbol MX',
    website: 'https://futbolmexico.mx',
    phone: '+52 55 5678 9012',
    country: 'Mexico',
    socialLinks: { youtube: 'CarlosFutbolTech' },
    promotionalChannels: ['Liga MX Youth Coaches', 'YouTube Tutorials'],
    referralCode: 'FUTBOLMX',
    tier: 'Silver',
    status: 'Active',
    joinDate: '2025-11-10',
    payoutMethod: 'Bank Transfer',
    payoutDetails: 'BBVA Mexico - CLABE: 0121 8000 1234 5678 90',
    stats: { totalClicks: 650, signups: 71, paidCustomers: 9, conversionRate: 0.045, totalRevenue: 3100, pendingCommission: 155, payableCommission: 310, totalEarned: 775, currentBalance: 310 },
  },
  {
    id: 'aff-23',
    name: 'Ethan White',
    email: 'ethan@rowingadmin.org',
    avatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150&auto=format&fit=crop&q=80',
    company: 'Rowing & Regatta Tech Solutions',
    website: 'https://rowingadmin.org',
    phone: '+1 (555) 789-2345',
    country: 'United States',
    socialLinks: { twitter: '@ethan_rowing' },
    promotionalChannels: ['USRowing Club Leaders Group', 'Regatta Central Blog'],
    referralCode: 'ROWTECH',
    tier: 'Bronze',
    status: 'Active',
    joinDate: '2026-01-30',
    payoutMethod: 'PayPal',
    payoutDetails: 'ethan@rowingadmin.org',
    stats: { totalClicks: 220, signups: 21, paidCustomers: 3, conversionRate: 0.038, totalRevenue: 950, pendingCommission: 50, payableCommission: 95, totalEarned: 190, currentBalance: 95 },
  },
  {
    id: 'aff-24',
    name: 'Samantha King',
    email: 'samantha@skiclubtech.ch',
    avatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150&auto=format&fit=crop&q=80',
    company: 'Alpine Winter Sports Alliance',
    website: 'https://skiclubtech.ch',
    phone: '+41 22 765 4321',
    country: 'Switzerland',
    socialLinks: { linkedin: 'samantha-king-ski' },
    promotionalChannels: ['FIS European Club Directors', 'Ski Academy Bulletin'],
    referralCode: 'ALPINETECH',
    tier: 'Silver',
    status: 'Active',
    joinDate: '2025-09-01',
    payoutMethod: 'Bank Transfer',
    payoutDetails: 'UBS Switzerland - CH93 0023 4567 8901 2345 A',
    stats: { totalClicks: 590, signups: 65, paidCustomers: 8, conversionRate: 0.044, totalRevenue: 2800, pendingCommission: 140, payableCommission: 280, totalEarned: 700, currentBalance: 280 },
  },
  {
    id: 'aff-25',
    name: 'Derrick Vance (Banned)',
    email: 'fraudster@fakebots.net',
    avatar: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=150&auto=format&fit=crop&q=80',
    company: 'Scam Marketing Co',
    website: 'https://fakebots.net',
    phone: '+1 (555) 999-8888',
    country: 'United States',
    socialLinks: {},
    promotionalChannels: ['Credit Card Fraud Ring', 'Chargeback Botnet'],
    referralCode: 'BANNEDBOT',
    tier: 'Bronze',
    status: 'Banned',
    joinDate: '2025-12-15',
    payoutMethod: 'PayPal',
    payoutDetails: 'fraudster@fakebots.net',
    stats: { totalClicks: 3200, signups: 15, paidCustomers: 0, conversionRate: 0.001, totalRevenue: 0, pendingCommission: 0, payableCommission: 0, totalEarned: 0, currentBalance: 0 },
    notes: ['Permanently banned for attempted stolen card signup abuse'],
  },
];

export const INITIAL_APPLICATIONS: Application[] = [
  {
    id: 'app-1',
    applicantName: 'Rachel Green',
    email: 'rachel@usyha.org',
    company: 'US Youth Handball Association',
    website: 'https://usyha.org',
    country: 'United States',
    phone: '+1 (555) 777-8899',
    promotionalChannel: 'Handball Association Newsletter (15k members)',
    audienceSize: '15,000+ Club Organizers',
    experienceDescription: 'We manage over 80 youth clubs across the US and frequently recommend club software to directors.',
    status: 'Pending',
    appliedDate: '2026-03-08',
  },
  {
    id: 'app-2',
    applicantName: 'Tomislav Horvat',
    email: 'tomi@waterpoloeurope.com',
    company: 'European Water Polo Directors',
    website: 'https://waterpoloeurope.com',
    country: 'Croatia',
    phone: '+385 1 234 5678',
    promotionalChannel: 'Water Polo Coaches Forum & Quarterly Summit',
    audienceSize: '5,000 Coaches & Admins',
    experienceDescription: 'Official partner for Adriatic water polo league club operations.',
    status: 'Pending',
    appliedDate: '2026-03-09',
  },
  {
    id: 'app-3',
    applicantName: 'Aisha Al-Mansoor',
    email: 'aisha@gulfsportsportal.ae',
    company: 'Gulf Youth Sports Academy Network',
    website: 'https://gulfsportsportal.ae',
    country: 'United Arab Emirates',
    phone: '+971 4 123 4567',
    promotionalChannel: 'UAE Sports Council Network & LinkedIn',
    audienceSize: '12,000 Sports Leaders',
    experienceDescription: 'Promoting modern management platforms to private academies in Dubai, Abu Dhabi and Doha.',
    status: 'Pending',
    appliedDate: '2026-03-09',
  },
  {
    id: 'app-4',
    applicantName: 'Kenji Sato',
    email: 'kenji@tokyojuniorsports.jp',
    company: 'Kanto Youth Sports Federation',
    website: 'https://tokyojuniorsports.jp',
    country: 'Japan',
    phone: '+81 3 5555 0123',
    promotionalChannel: 'Japanese Youth Sports Portal & YouTube Reviews',
    audienceSize: '25,000 Monthly Visitors',
    experienceDescription: 'Creating software comparison tutorials for youth baseball and soccer club boards in Japan.',
    status: 'Pending',
    appliedDate: '2026-03-10',
  },
  {
    id: 'app-5',
    applicantName: 'Gabriel Silva',
    email: 'gabriel@futsalbrasil.com.br',
    company: 'Federação Paulista de Futsal Coaches',
    website: 'https://futsalbrasil.com.br',
    country: 'Brazil',
    phone: '+55 11 98765 4321',
    promotionalChannel: 'Instagram & WhatsApp Director Groups (50k followers)',
    audienceSize: '50,000+ Community',
    experienceDescription: 'The largest futsal community in Brazil. Looking to partner with SquadDeck for South American clubs.',
    status: 'Pending',
    appliedDate: '2026-03-10',
  },
  {
    id: 'app-6',
    applicantName: 'Kari Lindqvist',
    email: 'kari@nordicfloorball.fi',
    company: 'Nordic Floorball Alliance',
    website: 'https://nordicfloorball.fi',
    country: 'Finland',
    phone: '+358 9 123 4567',
    promotionalChannel: 'Finnish & Swedish Floorball Clubs Association',
    audienceSize: '8,500 Club Admins',
    experienceDescription: 'Coordinating club digital transformations across Finland and Sweden.',
    status: 'Pending',
    appliedDate: '2026-03-11',
  },
  {
    id: 'app-7',
    applicantName: 'Zoe Campbell',
    email: 'zoe@scottishrugbyclubs.org.uk',
    company: 'Scottish Grassroots Rugby Portal',
    website: 'https://scottishrugbyclubs.org.uk',
    country: 'United Kingdom',
    phone: '+44 131 496 0000',
    promotionalChannel: 'Scottish Club Secretary Bulletin (400 clubs)',
    audienceSize: '400 Verified Sports Clubs',
    experienceDescription: 'We provide consultancy to volunteer committee boards looking for cloud roster and payment systems.',
    status: 'Pending',
    appliedDate: '2026-03-11',
  },
  {
    id: 'app-8',
    applicantName: 'Sanjay Patel',
    email: 'sanjay@indiacricketacademies.in',
    company: 'National Youth Cricket League',
    website: 'https://indiacricketacademies.in',
    country: 'India',
    phone: '+91 22 2456 7890',
    promotionalChannel: 'Cricket Academy Owners Association & YouTube channel',
    audienceSize: '30,000 Coaches & Parents',
    experienceDescription: 'Reviewing SaaS products for modernizing 300+ private cricket academies across Mumbai and Bangalore.',
    status: 'Pending',
    appliedDate: '2026-03-11',
  },
];

export const INITIAL_REFERRAL_LINKS: ReferralLink[] = [
  {
    id: 'link-1',
    affiliateId: 'aff-1',
    name: 'Main Basketball Youtube Link',
    code: 'JAMES123',
    url: 'https://squaddeck.com/join?ref=JAMES123',
    landingPage: '/sports/basketball',
    campaignId: 'camp-1',
    utmSource: 'youtube',
    utmMedium: 'video_description',
    utmCampaign: 'summer_growth_2026',
    clicks: 640,
    signups: 98,
    customers: 14,
    revenue: 4890,
    commission: 1222.5,
    status: 'Active',
    createdAt: '2025-08-16',
  },
  {
    id: 'link-2',
    affiliateId: 'aff-1',
    name: 'Coaches Podcast Promo',
    code: 'JAMESPOD',
    url: 'https://squaddeck.com/join?ref=JAMESPOD',
    landingPage: '/pricing',
    campaignId: 'camp-3',
    utmSource: 'podcast',
    utmMedium: 'audio_sponsor',
    utmCampaign: 'coach_referral_2026',
    clicks: 410,
    signups: 62,
    customers: 7,
    revenue: 2450,
    commission: 612.5,
    status: 'Active',
    createdAt: '2025-09-01',
  },
  {
    id: 'link-3',
    affiliateId: 'aff-1',
    name: 'Newsletter Exclusive Link',
    code: 'JAMESNEWS',
    url: 'https://squaddeck.com/join?ref=JAMESNEWS',
    landingPage: '/demo',
    campaignId: 'camp-4',
    utmSource: 'newsletter',
    utmMedium: 'email',
    utmCampaign: 'q1_growth',
    clicks: 198,
    signups: 26,
    customers: 3,
    revenue: 1080,
    commission: 270,
    status: 'Active',
    createdAt: '2026-01-10',
  },
  {
    id: 'link-4',
    affiliateId: 'aff-2',
    name: 'FA Grassroots Academy Header',
    code: 'SARAHFIT',
    url: 'https://squaddeck.com/join?ref=SARAHFIT',
    landingPage: '/sports/football',
    campaignId: 'camp-2',
    utmSource: 'grassroots_portal',
    utmMedium: 'banner',
    utmCampaign: 'football_club_special',
    clicks: 1820,
    signups: 215,
    customers: 31,
    revenue: 10580,
    commission: 3174,
    status: 'Active',
    createdAt: '2025-05-15',
  },
  {
    id: 'link-5',
    affiliateId: 'aff-3',
    name: 'Ontario Hockey Portal Sidebar',
    code: 'COACHDAN',
    url: 'https://squaddeck.com/join?ref=COACHDAN',
    landingPage: '/sports/hockey',
    campaignId: 'camp-1',
    utmSource: 'hockeygrowth',
    utmMedium: 'sidebar',
    utmCampaign: 'winter_season_2026',
    clicks: 3400,
    signups: 410,
    customers: 58,
    revenue: 23200,
    commission: 8120,
    status: 'Active',
    createdAt: '2025-02-10',
  },
];

export const INITIAL_CUSTOMERS: Customer[] = [
  {
    id: 'cust-1',
    orgName: 'Riverside Basketball Club',
    contactName: 'Coach Marcus Evans',
    email: 'marcus@riversidehoops.org',
    plan: 'Pro',
    signupDate: '2025-09-02',
    subscriptionStatus: 'Active',
    monthlyRevenue: 49,
    lifetimeRevenue: 294,
    commissionEarned: 73.5,
    affiliateId: 'aff-1',
    affiliateName: 'James Wilson',
    attribution: 'Last Touch (Link: JAMES123, YouTube)',
    campaign: 'Summer Sports Campaign',
    coupon: 'SQUADJAMES20',
    paymentHistory: [
      { id: 'pay-1', date: '2025-09-02', amount: 49, plan: 'Pro', status: 'Paid' },
      { id: 'pay-2', date: '2025-10-02', amount: 49, plan: 'Pro', status: 'Paid' },
      { id: 'pay-3', date: '2025-11-02', amount: 49, plan: 'Pro', status: 'Paid' },
      { id: 'pay-4', date: '2025-12-02', amount: 49, plan: 'Pro', status: 'Paid' },
      { id: 'pay-5', date: '2026-01-02', amount: 49, plan: 'Pro', status: 'Paid' },
      { id: 'pay-6', date: '2026-02-02', amount: 49, plan: 'Pro', status: 'Paid' },
    ],
    commissionHistory: [
      { id: 'comm-1', date: '2025-09-02', amount: 12.25, status: 'Paid' },
      { id: 'comm-2', date: '2025-10-02', amount: 12.25, status: 'Paid' },
      { id: 'comm-3', date: '2025-11-02', amount: 12.25, status: 'Paid' },
      { id: 'comm-4', date: '2025-12-02', amount: 12.25, status: 'Paid' },
      { id: 'comm-5', date: '2026-01-02', amount: 12.25, status: 'Paid' },
      { id: 'comm-6', date: '2026-02-02', amount: 12.25, status: 'Payable' },
    ],
  },
  {
    id: 'cust-2',
    orgName: 'Manchester Youth Football Academy',
    contactName: 'Ian Sterling',
    email: 'ian@manchesteryouthfc.co.uk',
    plan: 'Pro',
    signupDate: '2025-06-15',
    subscriptionStatus: 'Active',
    monthlyRevenue: 49,
    lifetimeRevenue: 441,
    commissionEarned: 132.3,
    affiliateId: 'aff-2',
    affiliateName: 'Sarah Mitchell',
    attribution: 'Last Touch (Link: SARAHFIT, FA Network)',
    campaign: 'Football Club Campaign',
    paymentHistory: [
      { id: 'pay-10', date: '2026-02-15', amount: 49, plan: 'Pro', status: 'Paid' },
      { id: 'pay-11', date: '2026-01-15', amount: 49, plan: 'Pro', status: 'Paid' },
    ],
    commissionHistory: [
      { id: 'comm-10', date: '2026-02-15', amount: 14.7, status: 'Payable' },
      { id: 'comm-11', date: '2026-01-15', amount: 14.7, status: 'Paid' },
    ],
  },
  {
    id: 'cust-3',
    orgName: 'Elite Hockey Association',
    contactName: 'Brian MacLeod',
    email: 'brian@elitehockey.ca',
    plan: 'Pro',
    signupDate: '2025-03-01',
    subscriptionStatus: 'Active',
    monthlyRevenue: 49,
    lifetimeRevenue: 588,
    commissionEarned: 205.8,
    affiliateId: 'aff-3',
    affiliateName: 'Daniel Carter',
    attribution: 'Last Touch (Link: COACHDAN, Ontario Forum)',
    campaign: 'Summer Sports Campaign',
    paymentHistory: [
      { id: 'pay-20', date: '2026-02-01', amount: 49, plan: 'Pro', status: 'Paid' },
    ],
    commissionHistory: [
      { id: 'comm-20', date: '2026-02-01', amount: 17.15, status: 'Payable' },
    ],
  },
  {
    id: 'cust-4',
    orgName: 'Northside Cricket Club',
    contactName: 'Sunil Sharma',
    email: 'admin@northsidecricket.org',
    plan: 'Starter',
    signupDate: '2025-10-12',
    subscriptionStatus: 'Active',
    monthlyRevenue: 19,
    lifetimeRevenue: 95,
    commissionEarned: 23.75,
    affiliateId: 'aff-11',
    affiliateName: 'Alexander Wright',
    attribution: 'Last Touch (Link: CRICKETPRO)',
    campaign: '2026 Growth Campaign',
    paymentHistory: [
      { id: 'pay-30', date: '2026-02-12', amount: 19, plan: 'Starter', status: 'Paid' },
    ],
    commissionHistory: [
      { id: 'comm-30', date: '2026-02-12', amount: 4.75, status: 'Payable' },
    ],
  },
  {
    id: 'cust-5',
    orgName: 'Premier Volleyball Academy',
    contactName: 'Jessica Thorne',
    email: 'director@premiervolley.com',
    plan: 'Pro',
    signupDate: '2025-10-20',
    subscriptionStatus: 'Active',
    monthlyRevenue: 49,
    lifetimeRevenue: 245,
    commissionEarned: 61.25,
    affiliateId: 'aff-5',
    affiliateName: 'Michael Anderson',
    attribution: 'Last Touch (Link: VBALLPRO)',
    campaign: 'Coach Referral Campaign',
    paymentHistory: [
      { id: 'pay-40', date: '2026-02-20', amount: 49, plan: 'Pro', status: 'Paid' },
    ],
    commissionHistory: [
      { id: 'comm-40', date: '2026-02-20', amount: 12.25, status: 'Payable' },
    ],
  },
  {
    id: 'cust-6',
    orgName: 'Apex Martial Arts Center',
    contactName: 'Master Kenji Wu',
    email: 'info@apexmartialarts.com',
    plan: 'Pro',
    signupDate: '2025-10-14',
    subscriptionStatus: 'Active',
    monthlyRevenue: 49,
    lifetimeRevenue: 245,
    commissionEarned: 61.25,
    affiliateId: 'aff-13',
    affiliateName: 'Marcus Vance',
    attribution: 'Last Touch (Link: DOJOTECH)',
    paymentHistory: [{ id: 'pay-50', date: '2026-02-14', amount: 49, plan: 'Pro', status: 'Paid' }],
    commissionHistory: [{ id: 'comm-50', date: '2026-02-14', amount: 12.25, status: 'Payable' }],
  },
  {
    id: 'cust-7',
    orgName: 'Metro Swimming League',
    contactName: 'Diane Campbell',
    email: 'diane@metroswim.org',
    plan: 'Pro',
    signupDate: '2026-01-18',
    subscriptionStatus: 'Active',
    monthlyRevenue: 49,
    lifetimeRevenue: 98,
    commissionEarned: 19.6,
    affiliateId: 'aff-4',
    affiliateName: 'Olivia Brown',
    attribution: 'Last Touch (Link: OLIVIASWIM)',
    paymentHistory: [{ id: 'pay-60', date: '2026-02-18', amount: 49, plan: 'Pro', status: 'Paid' }],
    commissionHistory: [{ id: 'comm-60', date: '2026-02-18', amount: 9.8, status: 'Payable' }],
  },
  {
    id: 'cust-8',
    orgName: 'Summit Athletics Club',
    contactName: 'Coach Ryan Peters',
    email: 'ryan@summitathletics.com',
    plan: 'Pro',
    signupDate: '2025-07-20',
    subscriptionStatus: 'Active',
    monthlyRevenue: 49,
    lifetimeRevenue: 392,
    commissionEarned: 117.6,
    affiliateId: 'aff-8',
    affiliateName: 'Sophia Martinez',
    attribution: 'Last Touch (Link: TRACKPRO)',
    paymentHistory: [{ id: 'pay-70', date: '2026-02-20', amount: 49, plan: 'Pro', status: 'Paid' }],
    commissionHistory: [{ id: 'comm-70', date: '2026-02-20', amount: 14.7, status: 'Payable' }],
  },
  {
    id: 'cust-9',
    orgName: 'Barcelona Padel Club',
    contactName: 'Jordi Alcantara',
    email: 'jordi@bcnpadel.cat',
    plan: 'Pro',
    signupDate: '2025-08-15',
    subscriptionStatus: 'Active',
    monthlyRevenue: 49,
    lifetimeRevenue: 343,
    commissionEarned: 85.75,
    affiliateId: 'aff-9',
    affiliateName: 'Lucas Garcia',
    attribution: 'Last Touch (Link: PADELSPAIN)',
    paymentHistory: [{ id: 'pay-80', date: '2026-02-15', amount: 49, plan: 'Pro', status: 'Paid' }],
    commissionHistory: [{ id: 'comm-80', date: '2026-02-15', amount: 12.25, status: 'Payable' }],
  },
  {
    id: 'cust-10',
    orgName: 'Sydney Netball Knights',
    contactName: 'Gemma Wilson',
    email: 'gemma@sydneynetball.com.au',
    plan: 'Starter',
    signupDate: '2025-11-01',
    subscriptionStatus: 'Active',
    monthlyRevenue: 19,
    lifetimeRevenue: 76,
    commissionEarned: 19.0,
    affiliateId: 'aff-6',
    affiliateName: 'Emma Taylor',
    attribution: 'Last Touch (Link: EMMANET)',
    paymentHistory: [{ id: 'pay-90', date: '2026-02-01', amount: 19, plan: 'Starter', status: 'Paid' }],
    commissionHistory: [{ id: 'comm-90', date: '2026-02-01', amount: 4.75, status: 'Payable' }],
  },
  {
    id: 'cust-11',
    orgName: 'Auckland Rugby Juniors',
    contactName: 'Tamati Walker',
    email: 'tamati@aucklandrugbyjrs.co.nz',
    plan: 'Starter',
    signupDate: '2025-12-05',
    subscriptionStatus: 'Active',
    monthlyRevenue: 19,
    lifetimeRevenue: 57,
    commissionEarned: 11.4,
    affiliateId: 'aff-7',
    affiliateName: 'David Thompson',
    attribution: 'Last Touch (Link: KIWIRUGBY)',
    paymentHistory: [{ id: 'pay-100', date: '2026-02-05', amount: 19, plan: 'Starter', status: 'Paid' }],
    commissionHistory: [{ id: 'comm-100', date: '2026-02-05', amount: 3.8, status: 'Payable' }],
  },
  {
    id: 'cust-12',
    orgName: 'Chesapeake Lacrosse Academy',
    contactName: 'Tyler Vance',
    email: 'tyler@chesapeakelax.org',
    plan: 'Starter',
    signupDate: '2026-02-10',
    subscriptionStatus: 'Active',
    monthlyRevenue: 19,
    lifetimeRevenue: 19,
    commissionEarned: 3.8,
    affiliateId: 'aff-10',
    affiliateName: 'Chloe Davis',
    attribution: 'Last Touch (Link: LAXPRO)',
    paymentHistory: [{ id: 'pay-110', date: '2026-02-10', amount: 19, plan: 'Starter', status: 'Paid' }],
    commissionHistory: [{ id: 'comm-110', date: '2026-02-10', amount: 3.8, status: 'Pending' }],
  },
  {
    id: 'cust-13',
    orgName: 'Texas Elite Baseball League',
    contactName: 'Hank Schrader',
    email: 'hank@texasbaseball.org',
    plan: 'Pro',
    signupDate: '2025-06-28',
    subscriptionStatus: 'Active',
    monthlyRevenue: 49,
    lifetimeRevenue: 441,
    commissionEarned: 132.3,
    affiliateId: 'aff-15',
    affiliateName: 'Brandon Hall',
    attribution: 'Last Touch (Link: BASEBALL99)',
    paymentHistory: [{ id: 'pay-120', date: '2026-02-28', amount: 49, plan: 'Pro', status: 'Paid' }],
    commissionHistory: [{ id: 'comm-120', date: '2026-02-28', amount: 14.7, status: 'Payable' }],
  },
  {
    id: 'cust-14',
    orgName: 'Tri-State Gymnastics Center',
    contactName: 'Linda Sterling',
    email: 'linda@tristategym.com',
    plan: 'Pro',
    signupDate: '2025-05-19',
    subscriptionStatus: 'Active',
    monthlyRevenue: 49,
    lifetimeRevenue: 490,
    commissionEarned: 147.0,
    affiliateId: 'aff-12',
    affiliateName: 'Jessica Miller',
    attribution: 'Last Touch (Link: GYMDIRECTOR)',
    paymentHistory: [{ id: 'pay-130', date: '2026-02-19', amount: 49, plan: 'Pro', status: 'Paid' }],
    commissionHistory: [{ id: 'comm-130', date: '2026-02-19', amount: 14.7, status: 'Payable' }],
  },
  {
    id: 'cust-15',
    orgName: 'Munich Tennis Club e.V.',
    contactName: 'Stefan Bauer',
    email: 'stefan@tennisclub-muenchen.de',
    plan: 'Starter',
    signupDate: '2026-01-25',
    subscriptionStatus: 'Active',
    monthlyRevenue: 19,
    lifetimeRevenue: 38,
    commissionEarned: 7.6,
    affiliateId: 'aff-14',
    affiliateName: 'Elena Rostova',
    attribution: 'Last Touch (Link: TENNISPRO)',
    paymentHistory: [{ id: 'pay-140', date: '2026-02-25', amount: 19, plan: 'Starter', status: 'Paid' }],
    commissionHistory: [{ id: 'comm-140', date: '2026-02-25', amount: 3.8, status: 'Pending' }],
  },
  {
    id: 'cust-16',
    orgName: 'Rockies Climbing Academy',
    contactName: 'Nate Collins',
    email: 'nate@rockiesclimb.com',
    plan: 'Pro',
    signupDate: '2025-11-04',
    subscriptionStatus: 'Active',
    monthlyRevenue: 49,
    lifetimeRevenue: 196,
    commissionEarned: 49.0,
    affiliateId: 'aff-17',
    affiliateName: 'Noah Bennett',
    attribution: 'Last Touch (Link: CLIMBTECH)',
    paymentHistory: [{ id: 'pay-150', date: '2026-02-04', amount: 49, plan: 'Pro', status: 'Paid' }],
    commissionHistory: [{ id: 'comm-150', date: '2026-02-04', amount: 12.25, status: 'Payable' }],
  },
  {
    id: 'cust-17',
    orgName: 'Dublin Hurling Association',
    contactName: 'Sean Murphy',
    email: 'sean@dublinhurling.ie',
    plan: 'Starter',
    signupDate: '2025-12-18',
    subscriptionStatus: 'Active',
    monthlyRevenue: 19,
    lifetimeRevenue: 57,
    commissionEarned: 11.4,
    affiliateId: 'aff-18',
    affiliateName: 'Liam O’Connor',
    attribution: 'Last Touch (Link: GAACLUB)',
    paymentHistory: [{ id: 'pay-160', date: '2026-02-18', amount: 19, plan: 'Starter', status: 'Paid' }],
    commissionHistory: [{ id: 'comm-160', date: '2026-02-18', amount: 3.8, status: 'Payable' }],
  },
  {
    id: 'cust-18',
    orgName: 'Broadcasting Dance Studio',
    contactName: 'Chloe Bennett',
    email: 'chloe@broadcastingdance.com',
    plan: 'Pro',
    signupDate: '2025-09-12',
    subscriptionStatus: 'Active',
    monthlyRevenue: 49,
    lifetimeRevenue: 294,
    commissionEarned: 73.5,
    affiliateId: 'aff-19',
    affiliateName: 'Mia Roberts',
    attribution: 'Last Touch (Link: DANCEPRO)',
    paymentHistory: [{ id: 'pay-170', date: '2026-02-12', amount: 49, plan: 'Pro', status: 'Paid' }],
    commissionHistory: [{ id: 'comm-170', date: '2026-02-12', amount: 12.25, status: 'Payable' }],
  },
];

export const INITIAL_REFERRALS: Referral[] = [
  {
    id: 'ref-1',
    affiliateId: 'aff-1',
    affiliateName: 'James Wilson',
    linkId: 'link-1',
    customerName: 'Marcus Evans',
    orgName: 'Riverside Basketball Club',
    email: 'marcus@riversidehoops.org',
    clickDate: '2025-09-01 14:20',
    signupDate: '2025-09-02 09:15',
    plan: 'Pro',
    status: 'Paid',
    revenue: 294,
    commission: 73.5,
    attributionType: 'Last Touch (90-day window)',
    campaign: 'Summer Sports Campaign',
    coupon: 'SQUADJAMES20',
    country: 'United States',
    lifecycleStep: 8,
  },
  {
    id: 'ref-2',
    affiliateId: 'aff-2',
    affiliateName: 'Sarah Mitchell',
    linkId: 'link-4',
    customerName: 'Ian Sterling',
    orgName: 'Manchester Youth Football Academy',
    email: 'ian@manchesteryouthfc.co.uk',
    clickDate: '2025-06-14 11:30',
    signupDate: '2025-06-15 16:45',
    plan: 'Pro',
    status: 'Paid',
    revenue: 441,
    commission: 132.3,
    attributionType: 'Last Touch (90-day window)',
    campaign: 'Football Club Campaign',
    country: 'United Kingdom',
    lifecycleStep: 8,
  },
  {
    id: 'ref-3',
    affiliateId: 'aff-3',
    affiliateName: 'Daniel Carter',
    linkId: 'link-5',
    customerName: 'Brian MacLeod',
    orgName: 'Elite Hockey Association',
    email: 'brian@elitehockey.ca',
    clickDate: '2025-02-28 18:10',
    signupDate: '2025-03-01 10:00',
    plan: 'Pro',
    status: 'Paid',
    revenue: 588,
    commission: 205.8,
    attributionType: 'Last Touch (90-day window)',
    campaign: 'Summer Sports Campaign',
    country: 'Canada',
    lifecycleStep: 8,
  },
  {
    id: 'ref-4',
    affiliateId: 'aff-11',
    affiliateName: 'Alexander Wright',
    customerName: 'Sunil Sharma',
    orgName: 'Northside Cricket Club',
    email: 'admin@northsidecricket.org',
    clickDate: '2025-10-10 08:30',
    signupDate: '2025-10-12 11:20',
    plan: 'Starter',
    status: 'Paid',
    revenue: 95,
    commission: 23.75,
    attributionType: 'Last Touch (90-day window)',
    campaign: '2026 Growth Campaign',
    country: 'United Kingdom',
    lifecycleStep: 8,
  },
  {
    id: 'ref-5',
    affiliateId: 'aff-5',
    affiliateName: 'Michael Anderson',
    customerName: 'Jessica Thorne',
    orgName: 'Premier Volleyball Academy',
    email: 'director@premiervolley.com',
    clickDate: '2025-10-18 19:40',
    signupDate: '2025-10-20 14:10',
    plan: 'Pro',
    status: 'Paid',
    revenue: 245,
    commission: 61.25,
    attributionType: 'Last Touch (90-day window)',
    campaign: 'Coach Referral Campaign',
    country: 'United States',
    lifecycleStep: 8,
  },
  {
    id: 'ref-6',
    affiliateId: 'aff-1',
    affiliateName: 'James Wilson',
    customerName: 'Kevin Scott',
    orgName: 'Lakeside Youth Track Team',
    email: 'kevin@lakesidetrack.org',
    clickDate: '2026-03-05 10:15',
    signupDate: '2026-03-06 14:20',
    plan: 'Free',
    status: 'Free',
    revenue: 0,
    commission: 0,
    attributionType: 'Last Touch (90-day window)',
    campaign: 'Summer Sports Campaign',
    country: 'United States',
    lifecycleStep: 3,
  },
  {
    id: 'ref-7',
    affiliateId: 'aff-1',
    affiliateName: 'James Wilson',
    customerName: 'Coach Travis Cole',
    orgName: 'Bay Area Hoops Foundation',
    email: 'travis@bayhoops.org',
    clickDate: '2026-03-08 17:50',
    signupDate: '2026-03-09 11:30',
    plan: 'Free',
    status: 'Trial',
    revenue: 0,
    commission: 0,
    attributionType: 'Last Touch (90-day window)',
    campaign: 'Coach Referral Campaign',
    country: 'United States',
    lifecycleStep: 3,
  },
  {
    id: 'ref-8',
    affiliateId: 'aff-2',
    affiliateName: 'Sarah Mitchell',
    customerName: 'Gareth Bale-Smith',
    orgName: 'Cardiff Juniors FC',
    email: 'gareth@cardiffjuniors.org.uk',
    clickDate: '2026-03-07 12:10',
    signupDate: '2026-03-08 09:00',
    plan: 'Free',
    status: 'Signed Up',
    revenue: 0,
    commission: 0,
    attributionType: 'Last Touch (90-day window)',
    campaign: 'Football Club Campaign',
    country: 'United Kingdom',
    lifecycleStep: 2,
  },
];

export const INITIAL_COMMISSIONS: Commission[] = [
  {
    id: 'comm-101',
    affiliateId: 'aff-1',
    affiliateName: 'James Wilson',
    customerId: 'cust-1',
    customerName: 'Marcus Evans',
    orgName: 'Riverside Basketball Club',
    plan: 'Pro',
    type: 'Recurring',
    baseAmount: 49,
    rate: 0.25,
    amount: 12.25,
    status: 'Payable',
    date: '2026-03-02',
    reference: 'COMM-REV-0941',
  },
  {
    id: 'comm-102',
    affiliateId: 'aff-1',
    affiliateName: 'James Wilson',
    customerId: 'cust-1',
    customerName: 'Marcus Evans',
    orgName: 'Riverside Basketball Club',
    plan: 'Pro',
    type: 'Recurring',
    baseAmount: 49,
    rate: 0.25,
    amount: 12.25,
    status: 'Approved',
    date: '2026-02-02',
    reference: 'COMM-REV-0882',
  },
  {
    id: 'comm-103',
    affiliateId: 'aff-1',
    affiliateName: 'James Wilson',
    customerId: 'cust-1',
    customerName: 'Marcus Evans',
    orgName: 'Riverside Basketball Club',
    plan: 'Pro',
    type: 'Recurring',
    baseAmount: 49,
    rate: 0.25,
    amount: 12.25,
    status: 'Paid',
    date: '2026-01-02',
    reference: 'COMM-REV-0799',
  },
  {
    id: 'comm-104',
    affiliateId: 'aff-2',
    affiliateName: 'Sarah Mitchell',
    customerId: 'cust-2',
    customerName: 'Ian Sterling',
    orgName: 'Manchester Youth Football Academy',
    plan: 'Pro',
    type: 'Recurring',
    baseAmount: 49,
    rate: 0.30,
    amount: 14.70,
    status: 'Payable',
    date: '2026-03-01',
    reference: 'COMM-REV-0938',
  },
  {
    id: 'comm-105',
    affiliateId: 'aff-3',
    affiliateName: 'Daniel Carter',
    customerId: 'cust-3',
    customerName: 'Brian MacLeod',
    orgName: 'Elite Hockey Association',
    plan: 'Pro',
    type: 'Recurring',
    baseAmount: 49,
    rate: 0.35,
    amount: 17.15,
    status: 'Payable',
    date: '2026-03-01',
    reference: 'COMM-REV-0935',
  },
  {
    id: 'comm-106',
    affiliateId: 'aff-11',
    affiliateName: 'Alexander Wright',
    customerId: 'cust-4',
    customerName: 'Sunil Sharma',
    orgName: 'Northside Cricket Club',
    plan: 'Starter',
    type: 'Recurring',
    baseAmount: 19,
    rate: 0.25,
    amount: 4.75,
    status: 'Payable',
    date: '2026-02-28',
    reference: 'COMM-REV-0921',
  },
  {
    id: 'comm-107',
    affiliateId: 'aff-5',
    affiliateName: 'Michael Anderson',
    customerId: 'cust-5',
    customerName: 'Jessica Thorne',
    orgName: 'Premier Volleyball Academy',
    plan: 'Pro',
    type: 'Recurring',
    baseAmount: 49,
    rate: 0.25,
    amount: 12.25,
    status: 'Payable',
    date: '2026-02-27',
    reference: 'COMM-REV-0919',
  },
  {
    id: 'comm-108',
    affiliateId: 'aff-13',
    affiliateName: 'Marcus Vance',
    customerId: 'cust-6',
    customerName: 'Master Kenji Wu',
    orgName: 'Apex Martial Arts Center',
    plan: 'Pro',
    type: 'Recurring',
    baseAmount: 49,
    rate: 0.25,
    amount: 12.25,
    status: 'Approved',
    date: '2026-02-25',
    reference: 'COMM-REV-0902',
  },
  {
    id: 'comm-109',
    affiliateId: 'aff-4',
    affiliateName: 'Olivia Brown',
    customerId: 'cust-7',
    customerName: 'Diane Campbell',
    orgName: 'Metro Swimming League',
    plan: 'Pro',
    type: 'Recurring',
    baseAmount: 49,
    rate: 0.20,
    amount: 9.80,
    status: 'Pending',
    date: '2026-03-04',
    reference: 'COMM-REV-0955',
  },
  {
    id: 'comm-110',
    affiliateId: 'aff-8',
    affiliateName: 'Sophia Martinez',
    customerId: 'cust-8',
    customerName: 'Coach Ryan Peters',
    orgName: 'Summit Athletics Club',
    plan: 'Pro',
    type: 'Recurring',
    baseAmount: 49,
    rate: 0.30,
    amount: 14.70,
    status: 'Payable',
    date: '2026-02-24',
    reference: 'COMM-REV-0899',
  },
  {
    id: 'comm-111',
    affiliateId: 'aff-9',
    affiliateName: 'Lucas Garcia',
    customerId: 'cust-9',
    customerName: 'Jordi Alcantara',
    orgName: 'Barcelona Padel Club',
    plan: 'Pro',
    type: 'Recurring',
    baseAmount: 49,
    rate: 0.25,
    amount: 12.25,
    status: 'Payable',
    date: '2026-02-22',
    reference: 'COMM-REV-0891',
  },
  {
    id: 'comm-112',
    affiliateId: 'aff-1',
    affiliateName: 'James Wilson',
    customerId: 'cust-1',
    customerName: 'Marcus Evans',
    orgName: 'Riverside Basketball Club',
    plan: 'Pro',
    type: 'Bonus',
    baseAmount: 100,
    rate: 1.0,
    amount: 100.0,
    status: 'Paid',
    date: '2025-11-15',
    reference: 'BONUS-MILE-001',
    note: 'First 10 Customers Milestone Bonus',
  },
];

export const INITIAL_PAYOUTS: Payout[] = [
  {
    id: 'payout-1',
    affiliateId: 'aff-1',
    affiliateName: 'James Wilson',
    amount: 720.0,
    method: 'PayPal',
    requestedDate: '2026-03-01 10:30',
    processedDate: '2026-03-02 14:15',
    status: 'Approved',
    reference: 'PAY-2026-0381',
    accountDetails: 'PayPal: james.wilson@coachhub.io',
    note: 'Regular monthly commission withdrawal',
  },
  {
    id: 'payout-2',
    affiliateId: 'aff-2',
    affiliateName: 'Sarah Mitchell',
    amount: 1450.0,
    method: 'Bank Transfer',
    requestedDate: '2026-03-01 09:10',
    processedDate: '2026-03-02 11:00',
    status: 'Processing',
    reference: 'PAY-2026-0379',
    accountDetails: 'Barclays UK: Sort 20-04-15 Acct 88392019',
  },
  {
    id: 'payout-3',
    affiliateId: 'aff-3',
    affiliateName: 'Daniel Carter',
    amount: 2890.0,
    method: 'Stripe Direct',
    requestedDate: '2026-02-28 16:45',
    processedDate: '2026-03-01 10:00',
    status: 'Paid',
    reference: 'PAY-2026-0365',
    accountDetails: 'Stripe: acct_1NJx8829FKKsL99',
  },
  {
    id: 'payout-4',
    affiliateId: 'aff-8',
    affiliateName: 'Sophia Martinez',
    amount: 1120.0,
    method: 'Stripe Direct',
    requestedDate: '2026-02-25 14:00',
    processedDate: '2026-02-26 15:30',
    status: 'Paid',
    reference: 'PAY-2026-0350',
    accountDetails: 'Stripe: acct_1LPs8849FKKsQ21',
  },
  {
    id: 'payout-5',
    affiliateId: 'aff-12',
    affiliateName: 'Jessica Miller',
    amount: 980.0,
    method: 'PayPal',
    requestedDate: '2026-03-03 11:20',
    status: 'Pending',
    reference: 'PAY-2026-0390',
    accountDetails: 'PayPal: jessica@gymnasticsmgmt.com',
  },
  {
    id: 'payout-6',
    affiliateId: 'aff-15',
    affiliateName: 'Brandon Hall',
    amount: 1280.0,
    method: 'PayPal',
    requestedDate: '2026-03-04 15:10',
    status: 'Pending',
    reference: 'PAY-2026-0395',
    accountDetails: 'PayPal: brandon@baseballmanagers.org',
  },
];

export const INITIAL_COUPONS: Coupon[] = [
  {
    id: 'coup-1',
    code: 'SQUADJAMES20',
    discount: '20% OFF First 3 Months',
    discountPercent: 20,
    affiliateId: 'aff-1',
    affiliateName: 'James Wilson',
    usageCount: 42,
    customersReferred: 18,
    revenueGenerated: 3680,
    commissionGenerated: 920,
    expirationDate: '2026-12-31',
    status: 'Active',
    description: 'Special 20% discount coupon for James Wilson basketball followers.',
  },
  {
    id: 'coup-2',
    code: 'SARAHFOOTBALL',
    discount: '15% Lifetime Discount',
    discountPercent: 15,
    affiliateId: 'aff-2',
    affiliateName: 'Sarah Mitchell',
    usageCount: 89,
    customersReferred: 34,
    revenueGenerated: 8400,
    commissionGenerated: 2520,
    expirationDate: '2026-12-31',
    status: 'Active',
    description: 'Exclusive UK Grassroots soccer academy coupon.',
  },
  {
    id: 'coup-3',
    code: 'HOCKEYVIP25',
    discount: '25% OFF Annual Plans',
    discountPercent: 25,
    affiliateId: 'aff-3',
    affiliateName: 'Daniel Carter',
    usageCount: 124,
    customersReferred: 52,
    revenueGenerated: 16500,
    commissionGenerated: 5775,
    expirationDate: '2026-12-31',
    status: 'Active',
    description: 'Ontario Hockey Association VIP partner code.',
  },
  {
    id: 'coup-4',
    code: 'COACHSPECIAL',
    discount: '10% OFF Starter / Pro',
    discountPercent: 10,
    usageCount: 210,
    customersReferred: 68,
    revenueGenerated: 11200,
    commissionGenerated: 2800,
    expirationDate: '2026-06-30',
    status: 'Active',
    description: 'Global campaign promotional code for certified coaches.',
  },
  {
    id: 'coup-5',
    code: 'VOLLEYPRO15',
    discount: '15% OFF Starter',
    discountPercent: 15,
    affiliateId: 'aff-5',
    affiliateName: 'Michael Anderson',
    usageCount: 28,
    customersReferred: 9,
    revenueGenerated: 1890,
    commissionGenerated: 472.5,
    expirationDate: '2026-12-31',
    status: 'Active',
    description: 'National Volleyball Directors summit exclusive coupon.',
  },
  {
    id: 'coup-6',
    code: 'TRACKSAVE20',
    discount: '20% OFF First 3 Months',
    discountPercent: 20,
    affiliateId: 'aff-8',
    affiliateName: 'Sophia Martinez',
    usageCount: 54,
    customersReferred: 21,
    revenueGenerated: 4900,
    commissionGenerated: 1470,
    expirationDate: '2026-09-30',
    status: 'Active',
    description: 'Athletics and Track Coaches promotion.',
  },
  {
    id: 'coup-7',
    code: 'SUMMERCOACH30',
    discount: '30% OFF First Month',
    discountPercent: 30,
    usageCount: 310,
    customersReferred: 95,
    revenueGenerated: 18400,
    commissionGenerated: 4600,
    expirationDate: '2025-08-31',
    status: 'Expired',
    description: 'Summer 2025 promotional blitz voucher.',
  },
  {
    id: 'coup-8',
    code: 'JAMESNEW50',
    discount: '50% OFF Month 1',
    discountPercent: 50,
    affiliateId: 'aff-1',
    affiliateName: 'James Wilson',
    usageCount: 0,
    customersReferred: 0,
    revenueGenerated: 0,
    commissionGenerated: 0,
    expirationDate: '2026-12-31',
    status: 'Pending',
    description: 'Requested customized promo code for upcoming spring tournament.',
  },
];

export const INITIAL_CAMPAIGNS: Campaign[] = [
  {
    id: 'camp-1',
    name: 'Summer Sports Campaign',
    description: 'Seasonal promotion targeting summer basketball, baseball, and aquatic clubs with subsidized onboarding.',
    status: 'Active',
    startDate: '2025-06-01',
    endDate: '2026-08-31',
    clicks: 4850,
    signups: 610,
    customers: 84,
    revenue: 34200,
    commission: 8550,
    assignedAffiliates: ['aff-1', 'aff-3', 'aff-4', 'aff-15'],
  },
  {
    id: 'camp-2',
    name: 'Football Club Campaign',
    description: 'Dedicated campaign for youth soccer academies, FA accredited grassroots leagues, and club directors in the UK & Europe.',
    status: 'Active',
    startDate: '2025-08-01',
    endDate: '2026-07-31',
    clicks: 3420,
    signups: 420,
    customers: 58,
    revenue: 22800,
    commission: 6840,
    assignedAffiliates: ['aff-2', 'aff-9', 'aff-22'],
  },
  {
    id: 'camp-3',
    name: 'Coach Referral Campaign',
    description: 'Incentive program rewarding coaching podcast hosts and influencers who recruit team organizers directly.',
    status: 'Active',
    startDate: '2025-09-01',
    endDate: '2026-12-31',
    clicks: 2980,
    signups: 340,
    customers: 45,
    revenue: 17400,
    commission: 4350,
    assignedAffiliates: ['aff-1', 'aff-5', 'aff-11', 'aff-13'],
  },
  {
    id: 'camp-4',
    name: '2026 Growth Campaign',
    description: 'Q1-Q2 cross-sport expansion drive across North America and Europe offering bonus tier perks.',
    status: 'Active',
    startDate: '2026-01-01',
    endDate: '2026-06-30',
    clicks: 1890,
    signups: 210,
    customers: 29,
    revenue: 11600,
    commission: 2900,
    assignedAffiliates: ['aff-1', 'aff-2', 'aff-3', 'aff-8', 'aff-12'],
  },
];

export const INITIAL_TIERS: Tier[] = [
  {
    id: 'tier-1',
    name: 'Bronze',
    minCustomers: 0,
    minRevenue: 0,
    commissionRate: 20,
    color: '#D97706',
    benefits: ['Standard 20% recurring commission', 'Standard marketing asset pack', 'Monthly automated payouts', 'Email support'],
  },
  {
    id: 'tier-2',
    name: 'Silver',
    minCustomers: 10,
    minRevenue: 1000,
    commissionRate: 25,
    color: '#64748B',
    benefits: ['Upgraded 25% recurring commission', 'Custom coupon code generator', 'Priority payout review', 'Dedicated affiliate manager'],
  },
  {
    id: 'tier-3',
    name: 'Gold',
    minCustomers: 25,
    minRevenue: 5000,
    commissionRate: 30,
    color: '#EAB308',
    benefits: ['High-earner 30% recurring commission', 'Custom co-branded landing pages', 'Bi-weekly payout options', 'VIP feature previews'],
  },
  {
    id: 'tier-4',
    name: 'Platinum',
    minCustomers: 50,
    minRevenue: 15000,
    commissionRate: 35,
    color: '#9333EA',
    benefits: ['Elite 35% recurring commission', 'Custom contract terms & bonus pool', 'Instant payout approvals', 'Annual SquadDeck Partner Summit invitation'],
  },
];

export const INITIAL_COMMISSION_RULES: CommissionRule[] = [
  {
    id: 'rule-1',
    planName: 'Starter',
    defaultRate: 25,
    bronzeRate: 20,
    silverRate: 25,
    goldRate: 30,
    platinumRate: 35,
    description: '$19/month Starter Plan — Default $4.75 commission per active subscription per month.',
  },
  {
    id: 'rule-2',
    planName: 'Pro',
    defaultRate: 25,
    bronzeRate: 20,
    silverRate: 25,
    goldRate: 30,
    platinumRate: 35,
    description: '$49/month Pro Plan — Default $12.25 commission per active subscription per month.',
  },
  {
    id: 'rule-3',
    planName: 'Enterprise',
    defaultRate: 20,
    bronzeRate: 15,
    silverRate: 20,
    goldRate: 25,
    platinumRate: 30,
    description: 'Custom Enterprise Plan — Custom tiered rate calculated on total contracted monthly value.',
  },
];

export const INITIAL_BONUSES: Bonus[] = [
  {
    id: 'bon-1',
    title: 'First 10 Customers Milestone',
    type: 'Customer Milestone',
    requirement: 'Refer 10 active paying sports organizations',
    reward: 100,
    progress: 7, // For James Wilson demo progress
    maxProgress: 10,
    achieved: false,
    affiliateId: 'aff-1',
    affiliateName: 'James Wilson',
  },
  {
    id: 'bon-2',
    title: '$1,000 Revenue Milestone',
    type: 'Revenue Milestone',
    requirement: 'Generate $1,000 in monthly recurring subscription revenue',
    reward: 150,
    progress: 1000,
    maxProgress: 1000,
    achieved: true,
    affiliateId: 'aff-1',
    affiliateName: 'James Wilson',
  },
  {
    id: 'bon-3',
    title: 'Silver to Gold Elevation Bonus',
    type: 'Tier Bonus',
    requirement: 'Reach 25 paying customers to unlock Gold Tier bonus payout',
    reward: 250,
    progress: 24,
    maxProgress: 25,
    achieved: false,
    affiliateId: 'aff-1',
    affiliateName: 'James Wilson',
  },
  {
    id: 'bon-4',
    title: 'Summer 2026 Blitz Champion',
    type: 'Campaign Bonus',
    requirement: 'Refer at least 15 teams during the Summer Sports Campaign',
    reward: 300,
    progress: 14,
    maxProgress: 15,
    achieved: false,
    affiliateId: 'aff-1',
    affiliateName: 'James Wilson',
  },
  {
    id: 'bon-5',
    title: 'March 2026 Sprint',
    type: 'Monthly Bonus',
    requirement: 'Acquire 5 new pro teams within the calendar month of March',
    reward: 100,
    progress: 2,
    maxProgress: 5,
    achieved: false,
    affiliateId: 'aff-1',
    affiliateName: 'James Wilson',
    expiryDate: '2026-03-31',
  },
  {
    id: 'bon-6',
    title: 'Top UK Referrer Q1',
    type: 'Campaign Bonus',
    requirement: 'Lead UK signups for Q1 2026',
    reward: 500,
    progress: 48,
    maxProgress: 50,
    achieved: false,
    affiliateId: 'aff-2',
    affiliateName: 'Sarah Mitchell',
  },
  {
    id: 'bon-7',
    title: 'Platinum Club 100 Customers',
    type: 'Customer Milestone',
    requirement: 'Surpass 100 active customers in a single calendar year',
    reward: 1000,
    progress: 85,
    maxProgress: 100,
    achieved: false,
    affiliateId: 'aff-3',
    affiliateName: 'Daniel Carter',
  },
  {
    id: 'bon-8',
    title: 'Spring Season Kickoff',
    type: 'Monthly Bonus',
    requirement: 'Refer 3 organizations in February',
    reward: 75,
    progress: 3,
    maxProgress: 3,
    achieved: true,
    affiliateId: 'aff-5',
    affiliateName: 'Michael Anderson',
  },
  {
    id: 'bon-9',
    title: 'Padel Expansion Award',
    type: 'Campaign Bonus',
    requirement: 'Sign up 10 Spanish padel clubs',
    reward: 200,
    progress: 9,
    maxProgress: 10,
    achieved: false,
    affiliateId: 'aff-9',
    affiliateName: 'Lucas Garcia',
  },
  {
    id: 'bon-10',
    title: 'First Customer Welcome Award',
    type: 'Customer Milestone',
    requirement: 'Sign up your first paying organization',
    reward: 50,
    progress: 1,
    maxProgress: 1,
    achieved: true,
    affiliateId: 'aff-4',
    affiliateName: 'Olivia Brown',
  },
];

export const INITIAL_FRAUD_CASES: FraudCase[] = [
  {
    id: 'fraud-1',
    affiliateId: 'aff-20',
    affiliateName: 'Victor Vance',
    type: 'Click Spam',
    riskScore: 'High',
    status: 'Suspended',
    flaggedDate: '2026-03-02 08:14',
    details: '1,420 rapid automated clicks detected from rotating proxy IP range (185.220.101.x) with 0.002% conversion rate.',
    ipAddress: '185.220.101.44',
  },
  {
    id: 'fraud-2',
    affiliateId: 'aff-25',
    affiliateName: 'Derrick Vance (Banned)',
    type: 'Chargeback Pattern',
    riskScore: 'Critical',
    status: 'Confirmed Fraud',
    flaggedDate: '2026-02-28 14:22',
    details: '4 consecutive chargebacks filed on newly upgraded accounts within 48 hours of signup using card testing scripts.',
    commissionAmount: 196.0,
  },
  {
    id: 'fraud-3',
    affiliateId: 'aff-10',
    affiliateName: 'Chloe Davis',
    type: 'Self Referral',
    riskScore: 'Medium',
    status: 'Under Review',
    flaggedDate: '2026-03-05 11:30',
    details: 'Customer signup credit card name matches affiliate registered legal name and billing postal code.',
    orgName: 'Davis Family Lacrosse Club',
    commissionAmount: 12.25,
  },
  {
    id: 'fraud-4',
    affiliateId: 'aff-4',
    affiliateName: 'Olivia Brown',
    type: 'Duplicate Organization',
    riskScore: 'Low',
    status: 'Resolved Safe',
    flaggedDate: '2026-02-20 16:40',
    details: 'Similar organization domain registered twice by same administrator under different sub-teams.',
    orgName: 'Metro Swimming Boys / Metro Swimming Girls',
  },
  {
    id: 'fraud-5',
    affiliateId: 'aff-13',
    affiliateName: 'Marcus Vance',
    type: 'Suspicious IP',
    riskScore: 'Medium',
    status: 'Under Review',
    flaggedDate: '2026-03-07 09:15',
    details: 'Referral click and customer checkout completed from identical datacenter IP address (AWS us-east-1).',
    ipAddress: '54.210.88.19',
    commissionAmount: 12.25,
  },
  {
    id: 'fraud-6',
    affiliateId: 'aff-1',
    affiliateName: 'James Wilson',
    type: 'Coupon Abuse',
    riskScore: 'Low',
    status: 'Resolved Safe',
    flaggedDate: '2026-01-15 13:20',
    details: 'High coupon usage spikes during YouTube live broadcast. Verified authentic coach audience.',
  },
  {
    id: 'fraud-7',
    affiliateId: 'aff-7',
    affiliateName: 'David Thompson',
    type: 'Abnormal Conversion',
    riskScore: 'Low',
    status: 'Resolved Safe',
    flaggedDate: '2026-02-12 10:00',
    details: '100% conversion rate across 5 targeted attendees from Auckland regional sports director seminar.',
  },
  {
    id: 'fraud-8',
    affiliateId: 'aff-14',
    affiliateName: 'Elena Rostova',
    type: 'Refund Pattern',
    riskScore: 'Medium',
    status: 'Under Review',
    flaggedDate: '2026-03-01 17:05',
    details: 'Customer initiated refund request within 24 hours of commission being approved.',
    commissionAmount: 3.8,
  },
  {
    id: 'fraud-9',
    affiliateId: 'aff-17',
    affiliateName: 'Noah Bennett',
    type: 'Suspicious IP',
    riskScore: 'Low',
    status: 'Resolved Safe',
    flaggedDate: '2026-02-14 18:30',
    details: 'VPN IP range detected during customer registration; verified legitimate climbing facility.',
  },
  {
    id: 'fraud-10',
    affiliateId: 'aff-19',
    affiliateName: 'Mia Roberts',
    type: 'Coupon Abuse',
    riskScore: 'Medium',
    status: 'Under Review',
    flaggedDate: '2026-03-08 15:45',
    details: 'Coupon code shared on public discount forum without authorization.',
  },
  {
    id: 'fraud-11',
    affiliateId: 'aff-21',
    affiliateName: 'Rebecca Scott',
    type: 'Self Referral',
    riskScore: 'Low',
    status: 'Under Review',
    flaggedDate: '2026-03-09 10:20',
    details: 'Affiliate email domain matches customer contact domain (@equestrianclubs.com).',
  },
  {
    id: 'fraud-12',
    affiliateId: 'aff-23',
    affiliateName: 'Ethan White',
    type: 'Duplicate Organization',
    riskScore: 'Low',
    status: 'Resolved Safe',
    flaggedDate: '2026-02-28 09:40',
    details: 'Affiliate assisted customer on-site during regatta registration.',
  },
  {
    id: 'fraud-13',
    affiliateId: 'aff-6',
    affiliateName: 'Emma Taylor',
    type: 'Abnormal Conversion',
    riskScore: 'Low',
    status: 'Resolved Safe',
    flaggedDate: '2026-01-20 14:10',
    details: 'High concentration of conversions within 2-hour conference presentation.',
  },
  {
    id: 'fraud-14',
    affiliateId: 'aff-11',
    affiliateName: 'Alexander Wright',
    type: 'Suspicious IP',
    riskScore: 'Medium',
    status: 'Under Review',
    flaggedDate: '2026-03-06 16:00',
    details: 'Unusual rapid clicking pattern from single Tor exit node.',
  },
  {
    id: 'fraud-15',
    affiliateId: 'aff-22',
    affiliateName: 'Carlos Mendoza',
    type: 'Refund Pattern',
    riskScore: 'Low',
    status: 'Resolved Safe',
    flaggedDate: '2026-02-18 11:30',
    details: 'Customer switched from Pro to Starter plan; prorated refund handled normally.',
  },
];

export const INITIAL_MARKETING_ASSETS: MarketingAsset[] = [
  {
    id: 'asset-1',
    title: 'SquadDeck Primary Vector Logo (Dark & Light)',
    category: 'Logos',
    description: 'High-resolution official SVG and PNG logos with dark and light variants for websites and docs.',
    dimensions: 'Vector / 2400x600',
    fileSize: '1.2 MB',
    format: 'SVG / PNG',
    previewUrl: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=400&auto=format&fit=crop&q=80',
    copyText: 'https://squaddeck.com/assets/brand/squaddeck-logo-kit.zip',
  },
  {
    id: 'asset-2',
    title: 'SquadDeck Icon Badge & Emblem',
    category: 'Logos',
    description: 'Square app icon badge suitable for video overlays, app reviews, and favicon sizing.',
    dimensions: '512x512',
    fileSize: '480 KB',
    format: 'PNG',
    previewUrl: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=400&auto=format&fit=crop&q=80',
    copyText: 'https://squaddeck.com/assets/brand/squaddeck-icon.png',
  },
  {
    id: 'asset-3',
    title: 'Summer Sports Web Leaderboard Banner',
    category: 'Banners',
    description: 'Header banner for sports blogs: "The #1 Cloud Management Platform for Youth Sports Clubs".',
    dimensions: '728x90',
    fileSize: '320 KB',
    format: 'PNG / HTML5',
    previewUrl: 'https://images.unsplash.com/photo-1546519638-68e109498ffc?w=400&auto=format&fit=crop&q=80',
    copyText: '<a href="https://squaddeck.com?ref={CODE}"><img src="https://squaddeck.com/banners/728x90-summer.png" alt="SquadDeck Sports Platform" /></a>',
  },
  {
    id: 'asset-4',
    title: 'Sidebar Medium Rectangle Ad Banner',
    category: 'Banners',
    description: 'High-converting sidebar banner for coaches forums and tournament portals.',
    dimensions: '300x250',
    fileSize: '210 KB',
    format: 'PNG',
    previewUrl: 'https://images.unsplash.com/photo-1574629810360-7efbbe195018?w=400&auto=format&fit=crop&q=80',
    copyText: '<a href="https://squaddeck.com?ref={CODE}"><img src="https://squaddeck.com/banners/300x250-coaches.png" alt="SquadDeck For Coaches" /></a>',
  },
  {
    id: 'asset-5',
    title: 'Skyscraper Vertical Display Banner',
    category: 'Banners',
    description: 'Vertical format banner designed for editorial sidebars and club association directories.',
    dimensions: '160x600',
    fileSize: '290 KB',
    format: 'PNG',
    previewUrl: 'https://images.unsplash.com/photo-1517649763962-0c623266ddc0?w=400&auto=format&fit=crop&q=80',
    copyText: '<a href="https://squaddeck.com?ref={CODE}"><img src="https://squaddeck.com/banners/160x600-vert.png" alt="Manage Your Sports Club" /></a>',
  },
  {
    id: 'asset-6',
    title: 'Instagram & Facebook Post: "Save 10+ Hours Every Week"',
    category: 'Social Media',
    description: 'Eye-catching social graphic detailing schedule management, automated fee collection and roster syncing.',
    dimensions: '1080x1080',
    fileSize: '1.4 MB',
    format: 'JPG',
    previewUrl: 'https://images.unsplash.com/photo-1526676037777-05a232554f77?w=400&auto=format&fit=crop&q=80',
    copyText: 'Still using spreadsheets to run your youth sports club? 🏀⚽ Switch to @SquadDeck to automate rosters, payments & game schedules in minutes. Use my code {CODE} for 20% off!',
  },
  {
    id: 'asset-7',
    title: 'Instagram Story & TikTok Vertical Template',
    category: 'Social Media',
    description: 'Vertical 9:16 template with swipe-up / link sticker placement area.',
    dimensions: '1080x1920',
    fileSize: '2.1 MB',
    format: 'MP4 / PNG',
    previewUrl: 'https://images.unsplash.com/photo-1517649763962-0c623266ddc0?w=400&auto=format&fit=crop&q=80',
    copyText: 'Check out SquadDeck for your sports team! Link in bio with discount code {CODE}.',
  },
  {
    id: 'asset-8',
    title: 'LinkedIn Thought Leadership Infographic',
    category: 'Social Media',
    description: 'Infographic: "How modern clubs increase registration revenue by 34% using cloud tools".',
    dimensions: '1200x627',
    fileSize: '890 KB',
    format: 'PNG',
    previewUrl: 'https://images.unsplash.com/photo-1551836022-d5d88e9218df?w=400&auto=format&fit=crop&q=80',
    copyText: 'For club directors and sports administrators: streamlining registration, attendance and parent messaging is no longer optional. Here is how SquadDeck transforms grassroots sports organizations.',
  },
  {
    id: 'asset-9',
    title: '60-Second SquadDeck Product Teaser Video',
    category: 'Videos',
    description: 'High-energy video with voiceover walking through roster creation, fee collection, and match scheduling.',
    dimensions: '1920x1080 (16:9)',
    fileSize: '28.4 MB',
    format: 'MP4 (1080p)',
    previewUrl: 'https://images.unsplash.com/photo-1574629810360-7efbbe195018?w=400&auto=format&fit=crop&q=80',
    copyText: 'SquadDeck 60s Overview Video - embed code: <iframe src="https://player.vimeo.com/video/squaddeck-promo" />',
  },
  {
    id: 'asset-10',
    title: 'YouTube 4K B-Roll & Screen Recording Pack',
    category: 'Videos',
    description: 'Clean UI screen captures, transitions, and product mockups ready to edit into software reviews.',
    dimensions: '3840x2160 (4K)',
    fileSize: '145 MB',
    format: 'ZIP (ProRes MP4)',
    previewUrl: 'https://images.unsplash.com/photo-1461896836934-ffe607ba8211?w=400&auto=format&fit=crop&q=80',
    copyText: 'https://squaddeck.com/assets/media/squaddeck-broll-pack-2026.zip',
  },
  {
    id: 'asset-11',
    title: 'High-Res Dashboard & Roster Screenshots Pack',
    category: 'Screenshots',
    description: 'Pixel-perfect screenshots of the SquadDeck dashboard, attendance tracker, and parent mobile app.',
    dimensions: '2560x1440',
    fileSize: '14.2 MB',
    format: 'PNG (Pack of 8)',
    previewUrl: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=400&auto=format&fit=crop&q=80',
    copyText: 'https://squaddeck.com/assets/media/squaddeck-screenshots-hd.zip',
  },
  {
    id: 'asset-12',
    title: 'Parent Mobile App Mockup in Hand',
    category: 'Screenshots',
    description: 'Photorealistic iPhone mockup showing live team chat, match check-in, and fee receipts.',
    dimensions: '2000x2000',
    fileSize: '3.8 MB',
    format: 'PNG',
    previewUrl: 'https://images.unsplash.com/photo-1512941937669-90a1b58e7e9c?w=400&auto=format&fit=crop&q=80',
  },
  {
    id: 'asset-13',
    title: 'Email Sequence: "Introduction to SquadDeck for Club Boards"',
    category: 'Email Templates',
    description: '3-part proven email sequence for emailing club presidents, directors, and head coaches.',
    dimensions: 'Text / HTML',
    fileSize: '45 KB',
    format: 'TXT / HTML',
    previewUrl: 'https://images.unsplash.com/photo-1596526131083-e8c633c948d2?w=400&auto=format&fit=crop&q=80',
    copyText: `Subject: Smarter management for [Club Name] this season\n\nHi [First Name],\n\nRunning a sports club shouldn't mean spending 15 hours a week chasing registrations and manual fee transfers.\n\nSquadDeck brings rosters, schedules, and online payments into one unified hub. You can test it out free here: https://squaddeck.com/join?ref={CODE}\n\nBest,\n[Your Name]`,
  },
  {
    id: 'asset-14',
    title: 'Email Template: "Special Discount for Our League Members"',
    category: 'Email Templates',
    description: 'Promotional announcement template introducing your affiliate coupon discount code.',
    dimensions: 'Text / HTML',
    fileSize: '38 KB',
    format: 'TXT / HTML',
    previewUrl: 'https://images.unsplash.com/photo-1596526131083-e8c633c948d2?w=400&auto=format&fit=crop&q=80',
    copyText: `Subject: Exclusive partner discount for [League/Club Name]\n\nHey Coaches & Board Members,\n\nWe partnered with SquadDeck to give our community 20% off their club management software. Use code {CODE} at checkout: https://squaddeck.com?ref={CODE}`,
  },
  {
    id: 'asset-15',
    title: 'SquadDeck 2-Page Executive Overview PDF',
    category: 'PDFs',
    description: 'Printable executive summary for board meetings and coaching committee reviews.',
    dimensions: 'Letter / A4 PDF',
    fileSize: '2.4 MB',
    format: 'PDF',
    previewUrl: 'https://images.unsplash.com/photo-1568667256549-094345857637?w=400&auto=format&fit=crop&q=80',
    copyText: 'https://squaddeck.com/assets/docs/squaddeck-executive-overview.pdf',
  },
  {
    id: 'asset-16',
    title: 'Feature Comparison Matrix PDF (SquadDeck vs Legacy Systems)',
    category: 'PDFs',
    description: 'Clear side-by-side comparison chart showing SquadDeck features vs TeamSnap, SportsEngine, and generic spreadsheets.',
    dimensions: 'Letter / A4 PDF',
    fileSize: '1.8 MB',
    format: 'PDF',
    previewUrl: 'https://images.unsplash.com/photo-1586281380349-632531db7ed4?w=400&auto=format&fit=crop&q=80',
    copyText: 'https://squaddeck.com/assets/docs/squaddeck-competitive-matrix.pdf',
  },
  {
    id: 'asset-17',
    title: 'Club Board Presentation Slide Deck (Keynote / PPT)',
    category: 'Sales Materials',
    description: '12-slide customizable presentation template to pitch SquadDeck adoption to school and club boards.',
    dimensions: '16:9 Presentation',
    fileSize: '8.9 MB',
    format: 'PPTX / Keynote',
    previewUrl: 'https://images.unsplash.com/photo-1557804506-669a67965ba0?w=400&auto=format&fit=crop&q=80',
    copyText: 'https://squaddeck.com/assets/docs/squaddeck-pitch-deck.pptx',
  },
  {
    id: 'asset-18',
    title: 'ROI Calculator Worksheet (Excel / Google Sheets)',
    category: 'Sales Materials',
    description: 'Interactive spreadsheet helping sports clubs calculate hours saved and unpaid fee recovery.',
    dimensions: 'Spreadsheet',
    fileSize: '340 KB',
    format: 'XLSX',
    previewUrl: 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=400&auto=format&fit=crop&q=80',
    copyText: 'https://squaddeck.com/assets/docs/squaddeck-roi-calculator.xlsx',
  },
  {
    id: 'asset-19',
    title: 'Official SquadDeck Brand Guidelines & Tone of Voice',
    category: 'Sales Materials',
    description: 'Guidelines on approved terminology, color codes, logo clear space, and compliance requirements.',
    dimensions: 'PDF',
    fileSize: '3.1 MB',
    format: 'PDF',
    previewUrl: 'https://images.unsplash.com/photo-1542744094-3a31f272c490?w=400&auto=format&fit=crop&q=80',
    copyText: 'https://squaddeck.com/assets/brand/squaddeck-brand-guidelines.pdf',
  },
  {
    id: 'asset-20',
    title: 'Affiliate Best Practices & Conversion Playbook',
    category: 'Sales Materials',
    description: 'Top strategies from Gold and Platinum affiliates on earning recurring commissions with sports organizations.',
    dimensions: 'PDF',
    fileSize: '1.9 MB',
    format: 'PDF',
    previewUrl: 'https://images.unsplash.com/photo-1434030216411-0b793f4b4173?w=400&auto=format&fit=crop&q=80',
    copyText: 'https://squaddeck.com/assets/docs/squaddeck-affiliate-playbook.pdf',
  },
];

export const INITIAL_NOTIFICATIONS: Notification[] = [
  {
    id: 'notif-1',
    title: 'New referral generated!',
    description: 'Marcus Evans from Riverside Basketball Club signed up using your link JAMES123.',
    date: '2026-03-09 11:30',
    read: false,
    type: 'success',
    link: '/affiliate/referrals',
  },
  {
    id: 'notif-2',
    title: 'Commission approved',
    description: '$12.25 recurring commission for Riverside Basketball Club (Pro Plan) was approved.',
    date: '2026-03-08 14:10',
    read: false,
    type: 'success',
    link: '/affiliate/commissions',
  },
  {
    id: 'notif-3',
    title: 'Payout processed',
    description: 'Your payout request of $720.00 has been approved and marked as paid via PayPal.',
    date: '2026-03-02 14:20',
    read: true,
    type: 'payout',
    link: '/affiliate/payouts',
  },
  {
    id: 'notif-4',
    title: 'Tier milestone near!',
    description: 'You are just 1 customer away from reaching the Gold Tier (30% commission rate).',
    date: '2026-02-28 09:00',
    read: true,
    type: 'tier',
    link: '/affiliate/bonuses',
  },
  {
    id: 'notif-5',
    title: 'Coupon SQUADJAMES20 used',
    description: 'A new organization applied your 20% discount coupon during onboarding.',
    date: '2026-02-25 16:45',
    read: true,
    type: 'info',
    link: '/affiliate/coupons',
  },
];

export const INITIAL_AUDIT_LOGS: AuditLog[] = [
  {
    id: 'audit-1',
    user: 'Admin (System)',
    action: 'Approved Affiliate Application',
    entity: 'Affiliate',
    entityId: 'aff-1',
    previousValue: 'Status: Pending',
    newValue: 'Status: Active (Tier: Silver)',
    reason: 'Verified coaching network credentials and YouTube audience.',
    timestamp: '2025-08-15 10:00',
  },
  {
    id: 'audit-2',
    user: 'James Wilson',
    action: 'Created Referral Link',
    entity: 'ReferralLink',
    entityId: 'link-1',
    previousValue: 'None',
    newValue: 'JAMES123 (Campaign: Summer Sports)',
    reason: 'Initial setup for YouTube video descriptions.',
    timestamp: '2025-08-16 11:20',
  },
  {
    id: 'audit-3',
    user: 'System Bot',
    action: 'Recorded Referral Click',
    entity: 'ReferralClick',
    entityId: 'click-0941',
    previousValue: '0 Clicks',
    newValue: '1 Click (IP: 73.189.20.14)',
    reason: 'Visitor clicked affiliate referral link from YouTube.',
    timestamp: '2025-09-01 14:20',
  },
  {
    id: 'audit-4',
    user: 'Marcus Evans',
    action: 'Customer Account Created',
    entity: 'Customer',
    entityId: 'cust-1',
    previousValue: 'None',
    newValue: 'Riverside Basketball Club (Free Plan)',
    reason: 'Attributed to James Wilson (JAMES123).',
    timestamp: '2025-09-02 09:15',
  },
  {
    id: 'audit-5',
    user: 'Marcus Evans',
    action: 'Customer Upgraded Subscription',
    entity: 'Customer',
    entityId: 'cust-1',
    previousValue: 'Plan: Free ($0/mo)',
    newValue: 'Plan: Pro ($49/mo)',
    reason: 'Customer upgraded to unlock full league management.',
    timestamp: '2025-09-02 09:30',
  },
  {
    id: 'audit-6',
    user: 'System Bot',
    action: 'Generated Commission',
    entity: 'Commission',
    entityId: 'comm-101',
    previousValue: 'None',
    newValue: '$12.25 (Pending Approval)',
    reason: 'Pro Plan $49.00 * 25% Silver rate.',
    timestamp: '2025-09-02 09:31',
  },
  {
    id: 'audit-7',
    user: 'Admin (Sarah Connor)',
    action: 'Approved Commission',
    entity: 'Commission',
    entityId: 'comm-101',
    previousValue: 'Status: Pending',
    newValue: 'Status: Approved',
    reason: 'Subscription charge cleared without dispute.',
    timestamp: '2025-09-03 14:00',
  },
  {
    id: 'audit-8',
    user: 'System Bot',
    action: 'Commission Made Payable',
    entity: 'Commission',
    entityId: 'comm-101',
    previousValue: 'Status: Approved',
    newValue: 'Status: Payable',
    reason: '30-day holding clearance period completed.',
    timestamp: '2025-10-02 00:00',
  },
  {
    id: 'audit-9',
    user: 'James Wilson',
    action: 'Requested Payout',
    entity: 'Payout',
    entityId: 'payout-1',
    previousValue: 'None',
    newValue: '$720.00 via PayPal',
    reason: 'Affiliate requested monthly withdrawal.',
    timestamp: '2026-03-01 10:30',
  },
  {
    id: 'audit-10',
    user: 'Admin (Finance Team)',
    action: 'Disbursed Payout',
    entity: 'Payout',
    entityId: 'payout-1',
    previousValue: 'Status: Pending Review',
    newValue: 'Status: Paid (Ref: PAY-2026-0381)',
    reason: 'PayPal batch disbursement completed successfully.',
    timestamp: '2026-03-02 14:15',
  },
];
